server:
  port: 8095

spring:
  application:
    name: msa-OAuth-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: thdtmdgk1!

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
  resource:
    jwt:
      key-value: jwt_secret_key

security.oauth2.client.client-secret=auth_secret
security.oauth2.resource.jwt.key-value=jwt_secret_key